import StaticPageLayout from "../components/StaticPageLayout";

export const metadata = { title: "Terms of Service — Clarity AI" };

export default function TermsPage() {
  return (
    <StaticPageLayout
      title="Terms of Service"
      subtitle="By using Clarity AI, you agree to these terms. Please read them carefully."
      lastUpdated="28 April 2026"
    >
      <h2>1. The service</h2>
      <p>
        Clarity AI (&quot;the Service&quot;) is operated by Shoka van Dooren (&quot;we&quot;, &quot;us&quot;, &quot;our&quot;), based in the Netherlands.
        The Service provides AI-powered text processing at vatoolai.com. By accessing or using the Service,
        you agree to be bound by these Terms of Service.
      </p>

      <h2>2. Free tier</h2>
      <p>
        The free tier allows 3 text processing requests per day. Free usage requires no account or registration.
        We reserve the right to adjust free tier limits at any time with reasonable notice.
      </p>

      <h2>3. Pro subscription</h2>
      <p>
        Pro access is offered at <strong>€9 per month</strong> and provides unlimited usage, all 11 modes, multiple
        platform social media, 15,000 character input, result history, and 3 variations per request.
      </p>
      <ul>
        <li>Subscriptions are billed monthly via Stripe</li>
        <li>You may cancel at any time from your Stripe billing portal; access continues until the end of the billing period</li>
        <li>Refunds are not guaranteed but may be considered at our discretion — email us within 7 days of a charge</li>
        <li>Prices may change with 30 days&apos; notice to existing subscribers</li>
      </ul>

      <h2>4. Acceptable use</h2>
      <p>You agree not to use the Service to:</p>
      <ul>
        <li>Generate content that is illegal, defamatory, harassing, or harmful</li>
        <li>Infringe any third party&apos;s intellectual property rights</li>
        <li>Attempt to reverse-engineer, scrape, or abuse the API</li>
        <li>Circumvent free-tier limits through automated requests</li>
        <li>Resell or sublicense access to the Service without written permission</li>
      </ul>
      <p>
        We reserve the right to suspend or terminate access for violations of these rules without notice or refund.
      </p>

      <h2>5. Your content</h2>
      <p>
        You retain full ownership of any text you submit to the Service. You grant us a limited, non-exclusive,
        royalty-free licence to process your text solely for the purpose of providing the Service. We do not store,
        share, or train AI models on your content.
      </p>

      <h2>6. AI-generated output</h2>
      <p>
        Outputs are generated by Claude, an AI model by Anthropic. AI outputs may be inaccurate, incomplete, or
        inappropriate. You are responsible for reviewing and verifying any output before using it. We make no
        warranties about the accuracy or fitness of AI-generated content for any purpose.
      </p>

      <h2>7. Availability</h2>
      <p>
        We aim for high availability but do not guarantee uptime. We may suspend the Service temporarily for
        maintenance, upgrades, or circumstances beyond our control. We are not liable for any losses arising from
        Service downtime.
      </p>

      <h2>8. Disclaimer of warranties</h2>
      <p>
        The Service is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind, express or implied,
        including but not limited to merchantability, fitness for a particular purpose, or non-infringement.
      </p>

      <h2>9. Limitation of liability</h2>
      <p>
        To the maximum extent permitted by law, we shall not be liable for any indirect, incidental, special,
        consequential, or punitive damages arising from your use of the Service, even if we have been advised of
        the possibility of such damages. Our total liability shall not exceed the amount you paid us in the
        30 days preceding the claim.
      </p>

      <h2>10. Governing law</h2>
      <p>
        These Terms are governed by the laws of the Netherlands. Any disputes shall be resolved in the courts of
        the Netherlands. If you are a consumer in the EU, mandatory consumer protection laws of your country of
        residence may also apply.
      </p>

      <h2>11. Changes to these Terms</h2>
      <p>
        We may update these Terms at any time. We will notify Pro subscribers of material changes by email at
        least 14 days in advance. Continued use of the Service after changes take effect constitutes acceptance.
      </p>

      <h2>12. Contact</h2>
      <p>
        Questions about these Terms? Use our <a href="/contact">contact form</a>.
      </p>
    </StaticPageLayout>
  );
}
